#!/usr/bin/env python3
"""Rewrite existing _posts front matter + _data/toc.yml without Notion cache.

Used when tools/cache/ is absent. Keep in sync with taxonomy.py rules.
Run: python3 tools/apply_taxonomy.py
"""
import glob
import os
import re

import taxonomy as T

HERE = os.path.dirname(__file__)
ROOT = os.path.abspath(os.path.join(HERE, ".."))
POSTS = os.path.join(ROOT, "_posts")
DATA = os.path.join(ROOT, "_data")

FM_RE = re.compile(r"^---\n(.*?)\n---\n?(.*)$", re.S)
FILE_SLUG_RE = re.compile(r"^\d{4}-\d{2}-\d{2}-(.+)\.md$")


def yaml_q(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def parse_list(raw):
    return re.findall(r'"([^"]*)"', raw or "")


def field(fm, name):
    m = re.search(rf"^{name}:\s*(.*)$", fm, re.M)
    return m.group(1).strip() if m else ""


def unquote(s):
    s = (s or "").strip()
    if len(s) >= 2 and s[0] == '"' and s[-1] == '"':
        return s[1:-1].replace('\\"', '"')
    return s


def permalink_of(filename, fm):
    explicit = field(fm, "permalink").strip().strip('"')
    if explicit:
        return explicit
    slug = FILE_SLUG_RE.match(os.path.basename(filename)).group(1)
    return f"/posts/{slug}/"


def refine(title, cats, body):
    if T._norm(title) in T.SKIP_TITLES:
        return None
    prim = cats[0] if cats else "기타"
    sec = cats[1] if len(cats) > 1 else "메모"
    if "콘솔만을 이용한 게시판" in title:
        prim, sec = "Java", "실습"
    new_title = T.display_title(title, sec, T.first_heading(body))
    prim, sec = T.uniquify(prim, sec)
    blob = f"{title} {new_title} {prim} {sec}".lower()
    tags = T._tags(prim, sec, blob, new_title)
    return new_title, [prim, sec], tags


def rebuild_toc(published):
    tree = {}
    for m in published:
        prim, sec = m["cats"]
        tree.setdefault(prim, {}).setdefault(sec, []).append(m)

    def dump_node(title, url, children, indent=0):
        pad = "  " * indent
        lines = [f"{pad}- title: {yaml_q(title)}", f"{pad}  url: {yaml_q(url)}"]
        if children:
            lines.append(f"{pad}  children:")
            lines.extend(children)
        return lines

    def cat_url(name):
        slug = re.sub(r"[^\w가-힣+]+", "-", name.lower()).strip("-")
        slug = slug.replace("+", "")
        return f"/categories/{slug}/"

    lines = ["# Generated by tools/apply_taxonomy.py — do not edit by hand.", ""]
    for prim in sorted(tree):
        sec_blocks = []
        for sec in sorted(tree[prim]):
            posts = sorted(tree[prim][sec], key=lambda x: x["title"])
            post_lines = []
            for m in posts:
                post_lines.extend(dump_node(m["title"], m["url"], [], 2))
            sec_blocks.extend(dump_node(sec, cat_url(sec), post_lines, 1))
        lines.extend(dump_node(prim, cat_url(prim), sec_blocks, 0))

    os.makedirs(DATA, exist_ok=True)
    with open(os.path.join(DATA, "toc.yml"), "w") as fh:
        fh.write("\n".join(lines) + "\n")


def main():
    published = []
    skipped = 0
    changed = 0
    for path in sorted(glob.glob(os.path.join(POSTS, "*.md"))):
        raw = open(path, encoding="utf-8").read()
        m = FM_RE.match(raw)
        if not m:
            raise SystemExit(f"no front matter: {path}")
        fm, body = m.group(1), m.group(2)
        title = unquote(field(fm, "title"))
        cats = parse_list(field(fm, "categories"))
        date = field(fm, "date")
        math = bool(re.search(r"^math:\s*true", fm, re.M))
        old_permalink = permalink_of(path, fm)

        refined = refine(title, cats, body)
        if refined is None:
            os.remove(path)
            skipped += 1
            print("skip", os.path.basename(path))
            continue
        new_title, new_cats, tags = refined
        lines = [
            "---",
            "title: " + yaml_q(new_title),
            "date: " + date,
            "categories: [" + ", ".join(yaml_q(c) for c in new_cats) + "]",
            "tags: [" + ", ".join(yaml_q(t) for t in tags) + "]",
        ]
        if math:
            lines.append("math: true")
        # Keep the already-published URL when the visible title changes.
        lines.append("permalink: " + old_permalink)
        lines.append("---")
        new_raw = "\n".join(lines) + "\n\n" + body.lstrip("\n")
        if new_raw != raw:
            open(path, "w", encoding="utf-8").write(new_raw)
            changed += 1
        published.append({"title": new_title, "cats": new_cats, "url": old_permalink})

    # Every secondary name must belong to one primary (flat Chirpy archives).
    seen = {}
    for m in published:
        sec = m["cats"][1]
        prim = m["cats"][0]
        if sec in seen and seen[sec] != prim:
            raise SystemExit(f"secondary collision: {sec} under {seen[sec]} and {prim}")
        seen[sec] = prim

    rebuild_toc(published)
    print(f"updated {changed} posts, removed {skipped}, published {len(published)}")
    print("wrote _data/toc.yml")


if __name__ == "__main__":
    main()
