#!/usr/bin/env python3
"""Convert cached Notion blocks into Chirpy posts with blog taxonomy.

Container/index pages are skipped. Categories are always 2-level so Chirpy
can expand them. Tags are derived from topic, not leftover Notion folders.
"""
import os
import re
import glob
import datetime

import notion_to_md as N
import taxonomy as T

HERE = os.path.dirname(__file__)
ROOT_DIR = os.path.abspath(os.path.join(HERE, ".."))
POSTS = os.path.join(ROOT_DIR, "_posts")
DATA = os.path.join(ROOT_DIR, "_data")

_slugs = {}
_used = set()
_meta = {}  # pid -> {title, cats, tags, url, publish}


def slug_of(pid):
    if pid in _slugs:
        return _slugs[pid]
    s = N.slugify(T.clean_title(N.raw_title(pid)), N.short(pid))
    if s in _used or len(s) > 60:
        s = (s[:60].rstrip("-") + "-" + N.short(pid))
    _used.add(s)
    _slugs[pid] = s
    return s


def cat_url(name):
    slug = re.sub(r"[^\w가-힣+]+", "-", name.lower()).strip("-")
    slug = slug.replace("+", "")  # jekyll slugify drops '+'
    return f"/categories/{slug}/"


def chirpy_permalink(pid):
    m = _meta.get(pid)
    if m and m.get("publish"):
        return f"/posts/{slug_of(pid)}/"
    if m and m.get("cats"):
        return cat_url(m["cats"][1] if len(m["cats"]) > 1 else m["cats"][0])
    return f"/posts/{slug_of(pid)}/"


def chirpy_title(pid):
    m = _meta.get(pid)
    return m["title"] if m else T.clean_title(N.raw_title(pid))


N.permalink = chirpy_permalink
N.nav_title = chirpy_title


def created_dt(pid):
    v = N.BLOCKS.get(pid, {})
    ms = v.get("created_time") or v.get("last_edited_time")
    if ms:
        return datetime.datetime.fromtimestamp(ms / 1000, tz=datetime.timezone.utc)
    return datetime.datetime(2021, 1, 1, tzinfo=datetime.timezone.utc)


def yaml_q(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def path_titles(pid):
    return [N.raw_title(a) for a in N.ancestors(pid)]


def has_real_body(v):
    for cid in v.get("content", []) or []:
        cv = N.BLOCKS.get(cid)
        if not cv or cv.get("type") in ("page", "divider"):
            continue
        if cv.get("type") in ("text", "bulleted_list", "numbered_list", "quote"):
            if not N.prop_text(cv).strip():
                continue
        return True
    return False


def write_toc_data(published):
    """Group published posts into _data/toc.yml: primary -> secondary -> posts."""
    tree = {}
    for pid in published:
        m = _meta[pid]
        prim, sec = m["cats"]
        tree.setdefault(prim, {}).setdefault(sec, []).append(m)

    def dump_node(title, url, children_yaml, indent=0):
        pad = "  " * indent
        lines = [f"{pad}- title: {yaml_q(title)}", f"{pad}  url: {yaml_q(url)}"]
        if children_yaml:
            lines.append(f"{pad}  children:")
            lines.extend(children_yaml)
        return lines

    lines = ["# Generated by tools/notion_to_chirpy.py — do not edit by hand.", ""]
    for prim in sorted(tree):
        sec_blocks = []
        for sec in sorted(tree[prim]):
            posts = sorted(tree[prim][sec], key=lambda m: m["title"])
            post_lines = []
            for m in posts:
                post_lines.extend(dump_node(m["title"], m["url"], [], 2))
            sec_blocks.extend(dump_node(sec, cat_url(sec), post_lines, 1))
        lines.extend(dump_node(prim, cat_url(prim), sec_blocks, 0))

    os.makedirs(DATA, exist_ok=True)
    with open(os.path.join(DATA, "toc.yml"), "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote _data/toc.yml")


def write_toc_tab():
    page = """---
title: 목차
icon: fas fa-sitemap
order: 1
---

글을 **주제 카테고리**로 다시 묶었습니다. 왼쪽 사이드바의 목차를 눌러도 같은 트리가 펼쳐집니다.

{% include toc-tree.html %}
"""
    os.makedirs(os.path.join(ROOT_DIR, "_tabs"), exist_ok=True)
    with open(os.path.join(ROOT_DIR, "_tabs", "toc.md"), "w") as fh:
        fh.write(page)
    print("wrote _tabs/toc.md")


def main():
    if os.path.isdir(POSTS):
        for f in glob.glob(os.path.join(POSTS, "*.md")):
            os.remove(f)
    os.makedirs(POSTS, exist_ok=True)

    # Classify first so permalinks exist before we render page mentions.
    for pid in N.PAGE_IDS:
        if pid == N.ROOT_ID:
            continue
        v = N.BLOCKS.get(pid) or {}
        kids = N.tree.get(pid, {}).get("children", [])
        bodyful = has_real_body(v)
        classified = T.classify(path_titles(pid), N.raw_title(pid), bool(kids), bodyful)
        title = T.clean_title(N.raw_title(pid))
        if classified is None:
            hint = T.classify(path_titles(pid) + [N.raw_title(pid)],
                              N.raw_title(pid), False, True)
            cats = [hint[0], hint[1]] if hint else ["기타", "메모"]
            _meta[pid] = {"title": title, "cats": cats, "tags": [],
                          "url": cat_url(cats[0]), "publish": False, "body": ""}
            continue
        prim, sec, tags = classified
        _meta[pid] = {"title": title, "cats": [prim, sec], "tags": tags,
                      "url": None, "publish": True, "body": ""}

    for pid, m in _meta.items():
        if m["publish"]:
            m["url"] = f"/posts/{slug_of(pid)}/"

    for pid, m in _meta.items():
        if not m["publish"]:
            continue
        v = N.BLOCKS.get(pid) or {}
        m["body"] = N.scrub_secrets(N.render_children(v)).strip()
        m["title"] = T.display_title(m["title"], m["cats"][1], T.first_heading(m["body"]))

    used_names = set()
    count = 0
    published = []
    for pid, m in _meta.items():
        if not m["publish"]:
            continue
        dt = created_dt(pid)
        fm = [
            "---",
            "title: " + yaml_q(m["title"]),
            "date: " + dt.strftime("%Y-%m-%d %H:%M:%S +0000"),
            "categories: [" + ", ".join(yaml_q(c) for c in m["cats"]) + "]",
            "tags: [" + ", ".join(yaml_q(t) for t in m["tags"]) + "]",
        ]
        if "\\(" in m["body"] or "$$" in m["body"]:
            fm.append("math: true")
        if N.slugify(m["title"], "") != slug_of(pid):
            fm.append("permalink: /posts/" + slug_of(pid) + "/")
        fm.append("---")
        name = f"{dt.strftime('%Y-%m-%d')}-{slug_of(pid)}.md"
        if name in used_names:
            name = f"{dt.strftime('%Y-%m-%d')}-{slug_of(pid)}-{N.short(pid)}.md"
        used_names.add(name)
        with open(os.path.join(POSTS, name), "w") as fh:
            fh.write("\n".join(fm) + "\n\n" + m["body"] + "\n")
        published.append(pid)
        count += 1

    print(f"wrote {count} Chirpy posts (skipped {sum(1 for m in _meta.values() if not m['publish'])} folders)")
    write_toc_data(published)
    write_toc_tab()


if __name__ == "__main__":
    main()
